server:
  port: 8082

spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/briiliomicroservice
    username: root
    password: root   

#to make application as eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    

